# First, generate some bikes
POST {{rental}}/?bikes=20&bikeType=city
Accept: application/json

###

# Show available bikes
GET {{rental}}/bikes
Accept: application/json

###

# Show bike status
GET {{rental}}/bikes/40208d8f-f338-4ba3-835e-b5026e6bde3e
Accept: application/json

###

# Request one of the available bikes
POST {{rental}}/requestBike?bikeId=ca78f8d5-86a6-4822-9db1-c757360ce8ce
Accept: application/json

###

# Find the payment for a specific payment reference
GET {{payment}}/findPayment?reference=ef6fdaa6-9be3-45a0-ab86-efcde226aea7
Accept: application/json

###

# Accept a payment
POST {{payment}}/acceptPayment?id=c5394643-cde7-4059-abf9-1d9c1389ad53
Accept: application/json

###

# Reject a payment
POST {{payment}}/rejectPayment?id=d8be5441-2fde-4bc4-b784-f375734509f9
Accept: application/json

###

# Show bike status
GET {{rental}}/bikes/91480d9a-20e3-43a7-a88f-8712365a4f4c
Accept: application/json

###

# Return a bike
POST {{rental}}/returnBike?bikeId=40208d8f-f338-4ba3-835e-b5026e6bde3e
Accept: application/json

###

# GENERATE RENTALS

POST {{rental}}/generateRentals?bikeType=city&loops=30&concurrency=10
Accept: text/plain

###
