### Generate bikes
# First, generate some bikes
POST {{rental}}/?bikes=20&bikeType=city
Accept: application/json

### List all
# Show available bikes
GET {{rental}}/bikes
Accept: application/json

### Bike status
# Show bike status
GET {{rental}}/bikes/28dc25a1-33cc-42fa-a660-cc19cb8711f1
Accept: application/json

### Request Bike
# Request one of the available bikes
POST {{rental}}/requestBike?bikeId=28dc25a1-33cc-42fa-a660-cc19cb8711f1
Accept: application/json

### Find paymentID
# Find the payment for a specific payment reference
GET {{payment}}/findPayment?reference=f9ad3f92-8a94-488c-b29e-f2c2c437b878
Accept: application/json

### Accept Payment
# Accept a payment
POST {{payment}}/acceptPayment?id=5588a0ca-c5b2-45e5-aa54-e9a80c91c549
Accept: application/json

### Reject Payment
# Reject a payment
POST {{payment}}/rejectPayment?id=d8be5441-2fde-4bc4-b784-f375734509f9
Accept: application/json

### Bike status (2)
# Show bike status
GET {{rental}}/bikes/91480d9a-20e3-43a7-a88f-8712365a4f4c
Accept: application/json

### Return bike
# Return a bike
POST {{rental}}/returnBike?bikeId=28dc25a1-33cc-42fa-a660-cc19cb8711f1
Accept: application/json

### Generate Rentals
POST {{rental}}/generateRentals?bikeType=city&loops=500&concurrency=10
Accept: text/plain
